apiVersion: apps/v1
kind: Deployment
metadata:
  name: tower-defense-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: towerdefensegame
    template:
      metadata:
        labels:
          app: tower-defense-game
      spec:
        containers:
        - name: tower-defense-container
          image: towerdefensegame
          ports:
          - containerPort: 8080